import time
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get("https://www.kamera-express.nl/")
time.sleep(5)
driver.maximize_window()
time.sleep(5)
# login
driver.find_element(By.XPATH,'//button[@class="is--regular"]').click()
time.sleep(5)
ct =driver.find_element(By.XPATH,'(//div[@class="login-button"])[2]')
a = ActionChains(driver)
a.move_to_element(ct).perform()
time.sleep(5)
driver.find_element(By.XPATH,'(//button[@class="sf-button"])[2]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//input[@name='username']").send_keys("sunilrathodn999@gmail.com")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@name='password']").send_keys("Naik@2025")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='btn_login']").click()
time.sleep(2)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
camera = driver.find_element(By.XPATH,"//div[@id='Producten-tab']//a[@id='tst-products-mainlist-link1']")
a = ActionChains(driver)
a.move_to_element(camera).perform()
time.sleep(5)
driver.find_element(By.XPATH,'//a[@id="systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='product-card-title-container']//p[contains(text(),'Sony A7 IV body')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
objective = driver.find_element(By.XPATH,'//a[@href="#objectieven"]')
a = ActionChains(driver)
a.move_to_element(objective).perform()
time.sleep(5)
driver.find_element(By.XPATH,'//a[@href="prime-lens"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Canon RF 50mm F/1.8 STM']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Statieven = driver.find_element(By.XPATH,'//a[@href="#fotostatief"]')
a = ActionChains(driver)
a.move_to_element(Statieven).perform()
time.sleep(5)
driver.find_element(By.XPATH,"//a[@id='tripod']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Kamera Express Essentials 170 Aluminium Statief']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='add-to-cart-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Video = driver.find_element(By.XPATH,'//a[@href="#video"]')
a = ActionChains(driver)
a.move_to_element(Video).perform()
time.sleep(5)
driver.find_element(By.XPATH,'//a[@id="camcorder"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Aquapix WDV5630 geel']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Tassen = driver.find_element(By.XPATH,'//a[@href="#tassen"]')
a = ActionChains(driver)
a.move_to_element(Tassen).perform()
time.sleep(5)
driver.find_element(By.XPATH,'//a[@href="rugzak"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Lowepro Tahoe BP 150 Black']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Studio = driver.find_element(By.XPATH,'//a[@href="#studio"]')
a = ActionChains(driver)
a.move_to_element(Studio).perform()
driver.find_element(By.XPATH,"//a[@id='complete-set-continu-licht']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Nanlite FS-300B LED Bi-color Spot light']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']").click()
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Beeldbewerking = driver.find_element(By.XPATH,'//a[@href="#beeldbewerking"]')
a = ActionChains(driver)
a.move_to_element(Beeldbewerking).perform()
driver.find_element(By.XPATH,'//a[@href="software"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='LiveU LRT cloud bonding service *DOWNLOAD*']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Audiotelevisie = driver.find_element(By.XPATH,'//a[@href="#beeld-en-geluid"]')
a = ActionChains(driver)
a.move_to_element(Audiotelevisie).perform()
driver.find_element(By.XPATH,'(//a[@href="microfoon-accessoires"])[2]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Rode Wireless GO III Charging Case+']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Verrekijkers = driver.find_element(By.XPATH,'//a[@href="#verrekijker-accessoires"]')
a = ActionChains(driver)
a.move_to_element(Verrekijkers).perform()
driver.find_element(By.XPATH,'//a[@href="verrekijker"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Steiner Wildlife 8x42']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Accessoires = driver.find_element(By.XPATH,'//a[@href="#accessoires"]')
a = ActionChains(driver)
a.move_to_element(Accessoires).perform()
driver.find_element(By.XPATH,'//a[@href="cleaning-kit"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Kamera Express Cleaning Kit']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='add-to-cart-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Outlet = driver.find_element(By.XPATH,'//a[@href="#outlet"]')
a = ActionChains(driver)
a.move_to_element(Outlet).perform()
driver.find_element(By.XPATH,'(//a[@href="outlet-camera"])[2]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Canon EOS R50 body OUTLET']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
Tweedehands = driver.find_element(By.XPATH,'//a[@href="#tweedehands-foto"]')
a = ActionChains(driver)
a.move_to_element(Tweedehands).perform()
driver.find_element(By.XPATH,'//a[@href="tweedehands-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//body/div[@id='__nuxt']/div[@id='__layout']/div/div/div/div[@id='plp-page-wrapper']/div[@class='plp-main']/div[@class='plp-main-content']/div[@class='product-grid']/a[1]/div[1]/div[2]/div[1]/p[1]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
product = driver.find_element(By.XPATH,'//a[@href="#Producten-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(product).perform()
acties = driver.find_element(By.XPATH,'(//a[@href="acties"])[2]')
a = ActionChains(driver)
a.move_to_element(acties).perform()
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
canon = driver.find_element(By.XPATH,'//a[@href="#canon"]')
a = ActionChains(driver)
a.move_to_element(canon).perform()
driver.find_element(By.XPATH,'//a[@href="canon-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='product-card-title-container']//p[contains(text(),'Canon EOS R6 mark II body')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']//div[@class='button-content']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
sony = driver.find_element(By.XPATH,'//a[@href="#sony"]')
a = ActionChains(driver)
a.move_to_element(sony).perform()
driver.find_element(By.XPATH,'//a[@href="sony-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='product-card-title-container']//p[contains(text(),'Sony A7 IV body')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']//div[@class='button-content']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
nikon = driver.find_element(By.XPATH,'//a[@href="#nikon"]')
a = ActionChains(driver)
a.move_to_element(nikon).perform()
driver.find_element(By.XPATH,'//a[@href="nikon-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='product-card-title-container']//p[contains(text(),'Nikon Z6 III body')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']//div[@class='button-content']//*[name()='svg']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
panasonic = driver.find_element(By.XPATH,'//a[@href="#panasonic"]')
a = ActionChains(driver)
a.move_to_element(panasonic).perform()
driver.find_element(By.XPATH,'//a[@href="panasonic-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[contains(text(),'Panasonic Lumix S9 Body Jet Black + LUMIX S 28-200')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
fujifilm = driver.find_element(By.XPATH,'//a[@href="#fujifilm"]')
a = ActionChains(driver)
a.move_to_element(fujifilm).perform()
driver.find_element(By.XPATH,'//a[@href="fujifilm-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Fujifilm X-E5 body zilver']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
sigma = driver.find_element(By.XPATH,'//a[@href="#sigma"]')
a = ActionChains(driver)
a.move_to_element(sigma).perform()
driver.find_element(By.XPATH,'//a[@href="sigma-primelens"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Sigma 30mm F/1.4 DC DN Contemporary Sony E']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
dji = driver.find_element(By.XPATH,'//a[@href="#dji"]')
a = ActionChains(driver)
a.move_to_element(dji).perform()
driver.find_element(By.XPATH,'//a[@href="dji-mini-drone"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='DJI Mini 5 Pro Fly More Combo + Smart Controller']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
leica = driver.find_element(By.XPATH,'//a[@href="#leica"]')
a = ActionChains(driver)
a.move_to_element(leica).perform()
driver.find_element(By.XPATH,'//a[@href="leica-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Leica 20229 M EV1']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
tamron = driver.find_element(By.XPATH,'//a[@href="#tamron"]')
a = ActionChains(driver)
a.move_to_element(tamron).perform()
driver.find_element(By.XPATH,'//a[@href="tamron-primelens"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Tamron 90mm f/2.8 Di III Macro VXD Sony FE']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
olympus = driver.find_element(By.XPATH,'//a[@href="#olympus"]')
a = ActionChains(driver)
a.move_to_element(olympus).perform()
driver.find_element(By.XPATH,'//a[@href="olympus-systeemcamera"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='product-card-title-container']//p[contains(text(),'OM SYSTEM OM-1 mark II body')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@class='full-width sf-button']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
epson = driver.find_element(By.XPATH,'//a[@href="#epson"]')
a = ActionChains(driver)
a.move_to_element(epson).perform()
driver.find_element(By.XPATH,'//a[@href="epson-ecotank-printers"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Epson EcoTank ET-16605']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
Merken = driver.find_element(By.XPATH,'//a[@href="#Merken-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Merken).perform()
merken = driver.find_element(By.XPATH,'//a[@href="merken"]')
a = ActionChains(driver)
a.move_to_element(merken).perform()
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
natuurfotografie = driver.find_element(By.XPATH,'//a[@href="#natuurfotografie"]')
a = ActionChains(driver)
a.move_to_element(natuurfotografie).perform()
driver.find_element(By.XPATH,"//a[contains(@href,'landschapsfotografie')]").click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
stadsfotografie = driver.find_element(By.XPATH,'//a[@href="#stadsfotografie"]')
a = ActionChains(driver)
a.move_to_element(stadsfotografie).perform()
driver.find_element(By.XPATH,'(//a[@id="urban-fotografie"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
modelfotografie = driver.find_element(By.XPATH,'//a[@href="#modelfotografie"]')
a = ActionChains(driver)
a.move_to_element(modelfotografie).perform()
driver.find_element(By.XPATH,'(//a[@id="portretfotografie"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
actiefotografie = driver.find_element(By.XPATH,'//a[@href="#actiefotografie"]')
a = ActionChains(driver)
a.move_to_element(actiefotografie).perform()
driver.find_element(By.XPATH,'(//a[@id="sportfotografie"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
reportagefotografie = driver.find_element(By.XPATH,'//a[@href="#reportagefotografie"]')
a = ActionChains(driver)
a.move_to_element(reportagefotografie).perform()
driver.find_element(By.XPATH,'(//a[@id="eventfotografie"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
studiofotografie = driver.find_element(By.XPATH,'//a[@href="#studiofotografie"]')
a = ActionChains(driver)
a.move_to_element(studiofotografie).perform()
driver.find_element(By.XPATH,'(//a[@id="foodfotografie"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
videografie = driver.find_element(By.XPATH,'//a[@href="#videografie"]')
a = ActionChains(driver)
a.move_to_element(videografie).perform()
driver.find_element(By.XPATH,'(//a[@id="vloggen"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
Inspiratie = driver.find_element(By.XPATH,'//a[@href="#Inspiratie-tab"]')
time.sleep(5)
a = ActionChains(driver)
a.move_to_element(Inspiratie).perform()
technieken = driver.find_element(By.XPATH,'//a[@href="#technieken"]')
a = ActionChains(driver)
a.move_to_element(technieken).perform()
driver.find_element(By.XPATH,'(//a[@id="drone-fotografie"])[2]').click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.find_element(By.XPATH,'//a[@href="opruiming"]').click()
time.sleep(5)
driver.find_element(By.XPATH,"//p[normalize-space()='Canon EF-S 18-55mm F/4.0-5.6 IS STM']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='button-text']").click()
time.sleep(5)
driver.back()
time.sleep(5)
driver.back()
time.sleep(5)
driver.find_element(By.XPATH,"//a[@class='dropdown-btn'][normalize-space()='Acties']")
time.sleep(5)